name: Daily Stock Scan
on:
  schedule:
    - cron: '0 21 * * *' # רץ כל לילה ב-23:00
  workflow_dispatch: # מאפשר הפעלה ידנית

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install yfinance requests pandas
      - name: Run bot
        run: python main.py

