name: Daily Stock Scan
on:
  schedule:
    - cron: '30 19 * * *' # 19:30 UTC זה 21:30 בישראל
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install yfinance requests pandas
      - name: Run bot
        run: python main.py
